{% set version = '1.12.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proc
  version: {{ version|replace("-", "_") }}

source:
  fn: pROC_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pROC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pROC/pROC_{{ version }}.tar.gz
  sha256: 9266a7d857313e36f86ad2a7e7b0d95240960a26707036409ac9776754324d15

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.1
    - r-ggplot2
    - r-plyr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.1
    - r-ggplot2
    - r-plyr

test:
  commands:
    - $R -e "library('pROC')"           # [not win]
    - "\"%R%\" -e \"library('pROC')\""  # [win]

about:
  home: http://expasy.org/tools/pROC/
  license: GPL (>= 3)
  summary: Tools for visualizing, smoothing and comparing receiver operating characteristic (ROC
    curves). (Partial) area under the curve (AUC) can be compared with statistical tests
    based on U-statistics or bootstrap. Confidence intervals can be computed for (p)AUC
    or ROC curves.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
