{% set version = "1.18.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pROC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pROC/pROC_{{ version }}.tar.gz
  sha256: d590ea7bab21559150ee58bc0833d41451c6ae6d33a725898dc190ba68c80a53

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-plyr                       # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.1
    - r-plyr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.11.1
    - r-plyr

test:
  commands:
    - $R -e "library('pROC')"           # [not win]
    - "\"%R%\" -e \"library('pROC')\""  # [win]

about:
  home: http://expasy.org/tools/pROC/
  dev_url: https://github.com/xrobin/pROC
  license: GPL-3.0-or-later
  summary: Tools for visualizing, smoothing and comparing receiver operating characteristic (ROC curves). (Partial) area under the curve (AUC) can be compared with statistical tests based on U-statistics or bootstrap. Confidence intervals can be computed for (p)AUC or ROC curves.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
